### ISSUE TITLE
Sơ đồ use case

### ISSUE THREAD

**Issue by NguyenNinh96** [BinhMai/CNPM_Group-8_Web_BanHang#11]

**Comment by vutuyetnhung** [comment]
![shop](https://user-images.githubusercontent.com/32647960/32909200-8ab6dfc4-cb38-11e7-926d-311c58460329.png)

**Comment by vutuyetnhung** [comment]
cái này có hơi khác cái hôm trước t vẽ tiếng việt ít, mn xem thiếu cái j k?

**Comment by NguyenNinh96** [comment]
ok
