### ISSUE TITLE
Mn cho phương án khi 1 khách hàng order thì nhân viên sẽ làm gì và làm sao để đến dc vs shipper??

### ISSUE THREAD

**Issue by binhhx96** [BinhMai/CNPM_Group-8_Web_BanHang#14]

**Comment by binhhx96** [comment]
Đầu tiên 1 mặt hàng khi ms order thì tk nhân viên vào sẽ có 1 ô checkout tức là chưa xác nhận đó, sau khi xác nhận thì sẽ check và order đó sẽ chuyển trạng thái transporting, nhưng khi đó ms là xác nhận thôi, còn phân shipper thế nào, shipper cũng nên có 1 trạng thái k nhể, đang rảnh, đang bận, hay đang vận chuyển r, hoặc có thể là shipper nay ốm chẳng hạn. còn nếu phân ok r thì shipper cũng có 1 ô checkout đã hoàn thành hay chưa, nếu check vào đó thì sẽ chuyển trạng thái finish.

**Comment by BichLoan482** [comment]
shipper nên có 2 ô để tích: nhận vận chuyển và đã chuyển xong

**Comment by binhhx96** [comment]
nếu như shipper đến tối ms đăng nhập thì sao, hoặc k onl thì sao???

Vào 21 Th11, 2017 12:54, "BichLoan482" <notifications@github.com> đã viết:

**Comment by BichLoan482** [comment]
thì là họ chưa nhận vận chuyển chứ sao

**Comment by min3rd** [comment]
t để thêm trường status vào chỗ order rồi nhé. hôm trước làm mà quên đấy

**Comment by binhhx96** [comment]
t thêm từ lâu r :v :v, vde là mình có nhiều shipper chứ k phải lúc nào cũng
chờ đứa đấy onl!!!!!

2017-11-21 23:35 GMT+07:00 9 Melody <notifications@github.com>:

**Comment by NguyenNinh96** [comment]
t tưởng k quan tâm đến thằng ship, ship không tham gia vào hệ thống bán, nhân viên nhận order thì sẽ tích vào ô đang vận chuyển sau đó giao ship xong sẽ tích vào ô hoàn thành chứ mình đâu cần quan tâm trạng thái ship

**Comment by ThoaPham96nd** [comment]
"nếu như shipper đến tối ms đăng nhập thì sao, hoặc k onl thì sao???" câu hỏi của Bình , t nghĩ auto là phải cập nhật  thông tin trong ngày trước 0h là được , mà thường giao dịch xong là check lại trạng thái giao dịch là "đã ship xong" luôn chứ, nghĩ đơn giản hóa đi

**Comment by binhhx96** [comment]
ý Ninh là nhân viên sẽ liên lạc vs shipper và sẽ làm nhiệm vụ giao hàng thủ công cho shipper, sau đó thêm mã shipper vào order và check đã giao hử?? đó cũng là 1 cách, liệu có cách nào khác k?

**Comment by min3rd** [comment]
Các bạn muốn làm nhỏ nhỏ, giờ lại to vl. Lazada và các trang ecommerce hiện tại họ có hệ thống ship riêng và có app cho shipper. Các bạn sẵn sàng là 1 quả app cho shipper k?

**Comment by NguyenNinh96** [comment]
ý t là không quản lý thằng ship

**Comment by NguyenNinh96** [comment]
t cũng thấy Bình nghĩ hơi phức tạp
