### ISSUE TITLE
Đề tài

### ISSUE THREAD

**Issue by NguyenNinh96** [BinhMai/CNPM_Group-8_Web_BanHang#2]

**Comment by binhhx96** [comment]
trang web bán hàng thì phải là online chứ.

**Comment by nguyenbs** [comment]
Anh thấy ý tưởng còn hơi sơ sài. 
1. Bán những mặt hàng gì? 
2. Có dịch vụ ship hàng không? 
3. Có thanh toán trực tuyến không? 
4. Hệ thống có những đối tượng người dùng nào? 
5. Sử dụng những công nghệ nào trên server, công nghệ nào dưới client (web, mobile)?

**Comment by vutuyetnhung** [comment]
Nếu là trang web bán đồ uống thì có thể phân chia thành các loại như
1. Cà phê
2. Sinh tố
3. Nước ép hoa quả
4. Trà
5. Sữa chua
6. Cocktail
7. Các loại thức uống khác(soda,....)

**Comment by ThoaPham96nd** [comment]
vote bán đồ ăn , đồ uống sẽ có nhiều hình ảnh cụ thể, đẹp , nội dung phong phú

**Comment by binhhx96** [comment]
Nhóm mình sẽ làm trang web bán đồ ăn và thức uống online qua dịch vụ ship hoặc thanh toán điện tử (hoặc cả 2 nếu dc), hệ thống sẽ có 4 đối tượng:
1.Khách hàng truy cập vào trang web kiểu khách: Nếu muốn đặt hàng thì phải tạo account
2. Khách hàng tạo 1 tài khoản user riêng: Có thanh toán theo kiểu ship hoặc thanh toán điện tử (nếu muốn)
3.Nhân viên thì admin sẽ tạo account: nhân viên đăng thông tin sản phẩm, trả lời comment, check order, shipper.
4, admin_quản lý order, doanh thu,...
Công nghệ_sử dụng framework laravel:
-server: php, mysql,..
-client: javascript, html, css, jquery, ajax,...
quản lý dự án bằng git. Ngoài ra có thể làm thêm chức năng sale, khuyến mãi, chăm sóc khách hàng.
