### ISSUE TITLE
Hệ thống có những đối tượng người dùng nào?

### ISSUE THREAD

**Issue by binhhx96** [BinhMai/CNPM_Group-8_Web_BanHang#3]

**Comment by binhhx96** [comment]
t nghĩ thì sẽ có 4 đối tượng
1. Khách hàng truy cập vào trang web kiểu khách_Nếu muốn đặt hàng thì phải tạo account
2. Khách hàng tạo 1 tài khoản user riêng_có thanh toán theo kiểu ship hoặc thanh toán điện tử (nếu muốn)
3. Nhân viên thì admin sẽ tạo account_nhân viên đăng thông tin sản phẩm, trả lời comment, check order 
4, admin_quản lý order, doanh thu,...

**Comment by BichLoan482** [comment]
t thấy cũng khá ổn r
khi làm cụ thể nếu thấy cần bổ sung cái gì thì mình thêm sau

**Comment by ThoaPham96nd** [comment]
theo t thì là nhân viên , admin hay khách đều phải có tài khoản mới tương tác được  tại sao k tạo ngay từ ban đầu , còn sợ khách ngại phải đăng nhập k mua hàng thì có thể để background bên ngaoif trang đăng nhập là ảnh với thông tin bán đồ ăn thức uống địa chỉ , tên web là đc

**Comment by ThoaPham96nd** [comment]
Như trang foody để xem ảnh cụ thể  phải click vào ảnh nó cũng bắt đăng nhập mới đc xem, không thì xem sơ sơ nội dung bên ngoài thôi, muốn cmt hỏi thêm thông tin thì lại tạo tài khoản mới đăng nhập đc, admin còn quản lí  số lượng người đang online , khách vào cmt trao đổi thông tin qua lại với nhau vui mà :v Sao lại k thích lập account luôn nhỉ :)))

**Comment by ThoaPham96nd** [comment]
Ý kiến riêng của t thôi , mn cứ thảo luận thêm hehe

**Comment by binhhx96** [comment]
bây h hiểu như là t chỉ ghé thăm page xem ntn thôi, nếu hay hoặc muốn ship hàng thì t ms dki thành viền, sao ép nta phải có tài khoản ms vào xem dc?

**Comment by binhhx96** [comment]
tạm thời là 4 đối tượng như t ns trên nha, ae chuyển sang issue khác? là ship và thanh toán, mời comment bên issue bên kia
