### ISSUE TITLE
Đẩy project lên host

### ISSUE THREAD

**Issue by binhhx96** [BinhMai/CNPM_Group-8_Web_BanHang#31]

**Comment by min3rd** [comment]
Upload lên rồi để link ở đây rồi close đi

**Comment by min3rd** [comment]
khi 1 issue close thì mới coi việc đó đã hoàn thành

**Comment by NguyenNinh96** [comment]
Bình đã upload xong chưa

**Comment by binhhx96** [comment]
link đây nha mn http://se2017s1g8.esy.es
