### ISSUE TITLE
Có dịch vụ ship hay thanh toán điện tử k?

### ISSUE THREAD

**Issue by binhhx96** [BinhMai/CNPM_Group-8_Web_BanHang#4]
nếu như ship thì tk ship sẽ phải có 1 tài khoản và quyền là ship, khi có 1 khách order muốn ship thì sẽ chuyển cho tk ship và nếu như ship xong thì tk ship phải tích là đã ship r. còn thanh toán điện tử thì mn có thể tham khảo trên mạng, t có xem r, còn k bk thực tế thì ntn chưa rõ?

**Comment by BichLoan482** [comment]
ship cũng có 2 kiểu thanh toán: trả = $ mặt hoặc thanh toán điện tử

**Comment by binhhx96** [comment]
thế chắc làm cả 2 r :)))

**Comment by BichLoan482** [comment]
trên thực tế nếu thanh toán điện tử mình phải đăng ký một tài khoản ngân hàng đặc biệt, cho phép kinh doanh thanh toán bằng thẻ tín dụng

**Comment by BichLoan482** [comment]
vì mình không có tài khoản đó nên mình sẽ nắm luôn cả quyền là ngân hàng, trường hợp khách chọn kiểu thanh toán điện tử, mình sẽ cho hiện 1 form yêu cầu nhập số tài khoản, mật khẩu, tên ngân hàng. Nếu đúng thì bắt đầu kiểm tra số $ trong tài khoản của họ. Trong trường hợp số $ tài khoản < số $ phải thanh toán, mình sẽ gửi họ 1 phản hồi với nội dung số $ thanh toán chưa đủ, yêu cầu họ kiểm tra lại hoặc thanh toán theo hình thức khac. Ngược lại gửi phản hồi thành công. Sau đó mình sẽ tự động trừ $ vào tài khoản của họ

**Comment by BichLoan482** [comment]
phải thêm 1 bảng quản lý tài khoản ngân hàng nữa

**Comment by binhhx96** [comment]
làm sao mà làm như thế được, chắc chắn là k, Loan nghĩ mình là hack hay sao mà đòi bk được tài khoản ngân hàng của nta là bao nhiêu tiền mà bảo là check này nọ, vs lại cứ coi như mình là ngân hàng đi, khi khách hàng cho tiền vào tk thì cậu định làm tnao, chắc chắn phải dùng tiền ảo và có cái nganhang.vn đó, t có xem, dùng cái đó thôi :)))

**Comment by BichLoan482** [comment]
ừ tất nhiên mọi thứ đều là ảo mà

**Comment by BichLoan482** [comment]
Bình nghĩ sao mà đòi có ng thanh toán thật ở đây :))))

**Comment by binhhx96** [comment]
cứ nghiên cứu tiếp đi Loan, t cũng chưa xem kĩ phần này cho lắm, nếu mà căng quá thì thôi cũng ksao :)

**Comment by ThoaPham96nd** [comment]
:))) Loan nói đúng mà , thanh toán ảo thì tạo tài khoản ngân hàng ảo cho khách thanh toán, mình có số tài khoản của khách , còn pass khách biết thôi mình k biết , số tiền trong tài khoản của khách cũng mình tự nhập vào csdl  . Ảo hết rồi còn gì ^^

**Comment by NguyenNinh96** [comment]
t nghĩ là ship thôi chứ k cần thanh toán điện tử. chỉ cần báo giá và nhận tiền khi ship

**Comment by vutuyetnhung** [comment]
nếu thanh toán chuyển khoản thì mình cần phải có liên kết vs ngân hàng hay gì đấy hoạt động kiểu như mấy cái máy quẹt thẻ nữa, nếu chỉ là thanh toán ảo thì phần này chả có nghĩa lý gì, t nghĩ là chỉ ship thôi
