### ISSUE TITLE
Họp triển khai dự án

### ISSUE THREAD

**Issue by binhhx96** [BinhMai/CNPM_Group-8_Web_BanHang#8]

**Comment by binhhx96** [comment]
Nhóm cố gắng tập trung 1 buổi hoặc 1 tiết để tập trung lại và bàn về những việc tiếp theo của nhóm, t nghĩ sẽ là 1t giữa của t2 hoặc t3. t vote tiết 3 thứ 2.

**Comment by NguyenNinh96** [comment]
ok. t cả 2 thời gian đấy đều ok.

**Comment by ThoaPham96nd** [comment]
okie nhé

**Comment by BichLoan482** [comment]
buổi nào cũng được nha

**Comment by vutuyetnhung** [comment]
t chọn tiết 3 của t3, k dc thì t2 cũng ok

**Comment by binhhx96** [comment]
chốt là tiết 3 ngày t2 nha, phòng thì có thể là căng tin nếu như k có phòng nha mn

**Comment by vutuyetnhung** [comment]
ok
